---
title: "p8105_hw6_yz4184"
author: "Yunlin Zhou"
date: "12/4/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(modelr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

### Load and clean the data

```{r}
birth_weight_df = read_csv("./birthweight.csv")%>%
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    gaweeks = round(gaweeks),
    malform = as.factor(malform),
    mrace = as.factor(mrace),
    ppbmi = round(ppbmi, digits = 3)
  )%>%
  drop_na()
  
```

### Set my own model

```{r}
fit = lm(bwt ~ gaweeks + mheight + ppbmi + ppwt, data = birth_weight_df)

residual_btw = modelr::add_residuals(birth_weight_df, fit)%>%select(resid)

prediction_btw = modelr::add_predictions(birth_weight_df, fit)%>%select(pred)

res_pred_df = cbind(residual_btw,
                     prediction_btw)
res_pred_df%>%
ggplot(aes(x = pred, y = resid)) +
  geom_point()+
  geom_smooth()
```

### 2 other models

```{r}
lm(bwt ~ blength + pnumsga, data = birth_weight_df)

lm(bwt ~ bhead * blength + blength * babysex + bhead * babysex + bhead * blength * babysex, data = birth_weight_df)
```

### Compare 3 models

```{r}
cv_df = 
  crossv_mc(birth_weight_df, 100) 

cv_df = 
  cv_df %>% 
  mutate(
    mod_1  = map(train, ~lm(bwt ~ gaweeks + mheight + ppbmi + ppwt, data = .x)),
    mod_2  = map(train, ~lm(bwt ~ blength + pnumsga, data = .x)),
    mod_3  = map(train, ~lm(bwt ~ bhead * blength + blength * babysex + bhead * babysex + bhead * blength * babysex, data = .x))) %>% 
  mutate(
    rmse_mod_1 = map2_dbl(mod_1, test, ~rmse(model = .x, data = .y)),
    rmse_mod_2 = map2_dbl(mod_2 , test, ~rmse(model = .x, data = .y)),
    rmse_mod_3 = map2_dbl(mod_3, test, ~rmse(model = .x, data = .y)))
```

### The distribution of RMSE values for each model

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```


## Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
bootstrap_r = 
  weather_df%>%
  bootstrap(n = 5000, id = "strap_number")%>%
 mutate(
    models =map(.x = strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)
    )%>%
  select(strap_number,results)%>%
  unnest(results)

bootstrap_r%>%
  ggplot(aes(x = adj.r.squared))+
  geom_histogram()

bootstrap_r %>% 
  summarize(
    ci_lower = quantile(adj.r.squared, 0.025), 
    ci_upper = quantile(adj.r.squared, 0.975))

```

```{r}
bootstrap_b = 
  weather_df%>%
  bootstrap(n = 5000, id = "strap_number")%>%
 mutate(
    models =map(.x = strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy))%>%
  select(strap_number,coeff)%>%
  unnest(results)

bootstrap_b%>%
  ggplot(aes(x = adj.r.squared))+
  geom_histogram()+
  facet_grid(~term, scales = "free"
  )

bootstrap_r %>% 
  summarize(
    ci_lower = quantile(adj.r.squared, 0.025), 
    ci_upper = quantile(adj.r.squared, 0.975))
```

